spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/volunteerAPI
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
application:
  auth:
    cookie-name: volunteerJWT
    jwt-secret: volunteerSecretKey
    jwt-expiration-time: 99999h