databaseChangeLog:
  - changeSet:
      id: insert-into-applications-table
      author: Batman
      changes:
        - insert:
            tableName: applications
            columns:
              - column:
                  name: event_id
                  value: 2
              - column:
                  name: user_id
                  value: 3e1ff2bc-744f-4836-8b4b-9a874d08b353
              - column:
                  name: status
                  value: WAITED
        - insert:
            tableName: applications
            columns:
              - column:
                  name: event_id
                  value: 3
              - column:
                  name: user_id
                  value: 3e1ff2bc-744f-4836-8b4b-9a874d08b353
              - column:
                  name: status
                  value: APPROVED
